Repository topk-io/topk, pull requests merged in 2025-08, with the labels that each got.

#186 vector -> list
  protos/topk/data/v1/expr/function.proto
  protos/topk/data/v1/value.proto
  topk-js/src/data/value.rs
  topk-js/src/data/vector/dense.rs
  topk-js/src/expr/function.rs
  topk-py/src/data/value.rs
  topk-py/src/data/vector/dense.rs
  topk-py/src/expr/function.rs
  topk-rs/src/lib.rs
  topk-rs/src/proto/data/v1/data_ext/mod.rs
  topk-rs/src/proto/data/v1/data_ext/value.rs
  topk-rs/src/proto/data/v1/data_ext/vector.rs
  topk-rs/src/proto/data/v1/mod.rs
  topk-rs/src/proto/data/v1/query_ext/expr_ext/function.rs
  topk-rs/tests/test_collection_upsert.rs
  topk-rs/tests/test_query_hybrid.rs
  topk-rs/tests/test_query_select.rs
  topk-rs/tests/test_query_sparse_vector.rs
  topk-rs/tests/test_query_vector.rs
  topk-rs/tests/utils/dataset/books.rs
Labels: ready

#187 [test] print debug info on fail
  topk-rs/tests/utils/mod.rs
Labels: self-approve

#188 [ci] earthly host ip override
  Earthfile
Labels: self-approve

#194 docs: lists
  docs/collections/create.mdx
  docs/documents/data-constructors.mdx
  docs/documents/query.mdx
  docs/documents/upsert.mdx
Labels: docs, ready

#193 [topk-rs] List contains and in_
  topk-rs/src/proto/data/v1/query_ext/expr_ext/logical.rs
  topk-rs/tests/test_query_filter_contains.rs
  topk-rs/tests/utils/dataset/books.rs
Labels: ready

#200 Use python3-venv package
  Earthfile
Labels: ready

#201 Output value is NativeValue
  topk-js/src/client/collection.rs
  topk-js/src/data/document.rs
  topk-js/src/data/mod.rs
  topk-js/src/data/value.rs
  topk-py/src/client/collection.rs
  topk-py/src/data/document.rs
  topk-py/src/data/mod.rs
  topk-py/src/data/value.rs
Labels: ready

#205 Add string list & f32_list constructors
  docs/documents/data-constructors.mdx
  docs/documents/upsert.mdx
  topk-js/index.d.ts
  topk-js/lib/data.d.ts
  topk-js/lib/data.js
  topk-js/src/data/mod.rs
  topk-js/tests/test_collection_upsert.spec.ts
  topk-js/tests/test_data_value.spec.ts
  topk-py/src/data/mod.rs
  topk-py/tests/test_collection_upsert.py
  topk-py/tests/test_data_list.py
  topk-py/tests/test_query_sparse_vector.py
  topk-py/topk_sdk/data/__init__.pyi
  topk-py/topk_sdk/query/__init__.pyi
Labels: docs, python, types, js, ready

#210 feat: List contains and in_
  topk-js/index.d.ts
  topk-js/src/expr/logical/binary_op.rs
  topk-js/src/expr/logical/flexible.rs
  topk-js/src/expr/logical/mod.rs
  topk-js/tests/test_query_filter_contains.spec.ts
  topk-py/src/expr/flexible.rs
  topk-py/src/expr/logical.rs
  topk-py/tests/test_collection_get.py
  topk-py/tests/test_query_filter_contains.py
  topk-py/tests/utils/dataset.py
  topk-py/topk_sdk/query/__init__.pyi
Labels: python, js, ready

#212 feat: any/all
  topk-js/index.d.ts
  topk-js/lib/query.d.ts
  topk-js/lib/query.js
  topk-js/src/expr/logical/mod.rs
  topk-js/src/expr/logical/nary_op.rs
  topk-js/src/query/mod.rs
  topk-js/tests/test_query_logical_nary.spec.ts
  topk-py/src/expr/logical.rs
  topk-py/src/query/mod.rs
  topk-py/tests/test_query_logical_nary.py
  topk-py/tests/utils/dataset.py
  topk-py/topk_sdk/query/__init__.pyi
Labels: python, js, ready
