Repository topk-io/topk, pull requests merged in 2025-04, with the labels that each got.

#17 [protos] fix `null` constructor
  topk-protos/src/data/v1/value_ext.rs
Labels: ready

#26 add `topk-rs` tests
  .github/workflows/pr.yml
  Earthfile
  topk-rs/Cargo.toml
  topk-rs/tests/test_collection.rs
  topk-rs/tests/test_delete.rs
  topk-rs/tests/test_get.rs
  topk-rs/tests/test_query_count.rs
  topk-rs/tests/test_query_filter.rs
  topk-rs/tests/test_query_logical.rs
  topk-rs/tests/test_query_select.rs
  topk-rs/tests/test_query_select_union.rs
  topk-rs/tests/test_query_text.rs
  topk-rs/tests/test_query_unified.rs
  topk-rs/tests/test_query_validation.rs
  topk-rs/tests/test_query_vector.rs
  topk-rs/tests/test_semantic_index.rs
  topk-rs/tests/test_upsert.rs
  topk-rs/tests/utils/dataset/books.rs
  topk-rs/tests/utils/dataset/mod.rs
  topk-rs/tests/utils/dataset/semantic.rs
  topk-rs/tests/utils/mod.rs
  topk-rs/tests/utils/test_context/mod.rs
  topk-rs/tests/utils/test_context/project.rs
Labels: ready

#27 fluent query builder for `topk-rs`
  topk-protos/src/data/v1/query_ext.rs
  topk-py/src/client/collection.rs
  topk-py/src/data/expr_binary.rs
  topk-py/src/data/expr_unary.rs
  topk-py/src/data/filter_expr.rs
  topk-py/src/data/flexible_expr.rs
  topk-py/src/data/function_expr.rs
  topk-py/src/data/logical_expr.rs
  topk-py/src/data/query.rs
  topk-py/src/data/scalar.rs
  topk-py/src/data/select_expr.rs
  topk-py/src/data/stage.rs
  topk-py/src/data/text_expr.rs
  topk-py/src/data/value.rs
  topk-py/src/query.rs
  topk-rs/src/client.rs
  topk-rs/src/data/expr_binary.rs
  topk-rs/src/data/expr_unary.rs
  topk-rs/src/data/filter_expr.rs
  topk-rs/src/data/function_expr.rs
  topk-rs/src/data/logical_expr.rs
  topk-rs/src/data/mod.rs
  topk-rs/src/data/scalar.rs
  topk-rs/src/data/select_expr.rs
  topk-rs/src/data/stage.rs
  topk-rs/src/data/text_expr.rs
  topk-rs/src/lib.rs
  topk-rs/src/query.rs
  topk-rs/tests/test_delete.rs
  topk-rs/tests/test_query_count.rs
  topk-rs/tests/test_query_filter.rs
  topk-rs/tests/test_query_logical.rs
  topk-rs/tests/test_query_select.rs
  topk-rs/tests/test_query_select_union.rs
  topk-rs/tests/test_query_text.rs
  topk-rs/tests/test_query_unified.rs
  topk-rs/tests/test_query_validation.rs
  topk-rs/tests/test_query_vector.rs
  topk-rs/tests/test_semantic_index.rs
  topk-rs/tests/utils/dataset/books.rs
  topk-rs/tests/utils/dataset/semantic.rs
Labels: ready

#30 [py] rename `gt_eq`/`lt_eq` to `gte`/`lte`
  topk-py/src/expr/logical.rs
Labels: ready

#33 napi skip gh release | remove freebsd | new version
  topk-js/npm/freebsd-x64/README.md
  topk-js/npm/freebsd-x64/package.json
  topk-js/package.json
Labels: ready

#38 Add x86_64-apple-darwin to topk-js triples
  topk-js/package.json
Labels: ready

#39 Extract query.rerank() arguments into a struct
  topk-js/index.d.ts
  topk-js/package.json
  topk-js/src/query/query.rs
  topk-js/tests/semantic_index.spec.ts
Labels: js, ready

#43 pass struct to vector field constructors | make semantic index arguments optional
  topk-js/index.d.ts
  topk-js/package.json
  topk-js/src/schema/mod.rs
  topk-js/tests/collections.spec.ts
  topk-js/tests/documents.spec.ts
  topk-js/tests/query_select.spec.ts
  topk-js/tests/query_vector.spec.ts
  topk-js/tests/semantic_index.spec.ts
Labels: js, ready

#41 drop `top_k()` and `count()` query builders
  topk-js/index.d.ts
  topk-js/lib/query.d.ts
  topk-js/lib/query.js
  topk-js/src/query/query.rs
  topk-js/tests/query_count.spec.ts
  topk-js/tests/query_topk.spec.ts
  topk-py/src/query/mod.rs
  topk-py/tests/test_delete.py
  topk-py/tests/test_query_select.py
  topk-py/tests/test_query_validation.py
  topk-rs/src/query/mod.rs
  topk-rs/tests/test_delete.rs
  topk-rs/tests/test_query_select.rs
  topk-rs/tests/test_query_validation.rs
Labels: ready

#49 topk-js docs: add ssr config information
  docs/quickstart.mdx
Labels: docs, js

#52 [publish] remove publish on tag
  .github/workflows/js.yml
  .github/workflows/python.yml
  topk-py/Cargo.toml
Labels: ready

#51 docs: add contains operator
  docs/documents/query.mdx
Labels: docs, python, js

#48 rename top_k in py and rs -> topk
  docs/concepts/semantic-search.mdx
  docs/concepts/unified-retrieval.mdx
  docs/documents/query.mdx
  docs/quickstart.mdx
  topk-protos/src/data/v1/query_ext.rs
  topk-py/README.md
  topk-py/src/query/query.rs
  topk-py/tests/test_delete.py
  topk-py/tests/test_query_filter_contains.py
  topk-py/tests/test_query_filter_not.py
  topk-py/tests/test_query_filter_starts_with.py
  topk-py/tests/test_query_logical.py
  topk-py/tests/test_query_select.py
  topk-py/tests/test_query_select_union.py
  topk-py/tests/test_query_text.py
  topk-py/tests/test_query_validation.py
  topk-py/tests/test_query_vector.py
  topk-py/tests/test_semantic_index.py
  topk-rs/src/query/query.rs
  topk-rs/src/query/stage.rs
  topk-rs/tests/test_delete.rs
  topk-rs/tests/test_query_filter_contains.rs
  topk-rs/tests/test_query_filter_not.rs
  topk-rs/tests/test_query_filter_starts_with.rs
  topk-rs/tests/test_query_logical.rs
  topk-rs/tests/test_query_select.rs
  topk-rs/tests/test_query_select_union.rs
  topk-rs/tests/test_query_text.rs
  topk-rs/tests/test_query_unified.rs
  topk-rs/tests/test_query_validation.rs
  topk-rs/tests/test_query_vector.rs
  topk-rs/tests/test_semantic_index.rs
Labels: docs, python, rust, ready

#50 Better error handling & formatting
  topk-js/package.json
  topk-js/src/error.rs
  topk-js/tests/collection.spec.ts
  topk-js/tests/collections.spec.ts
  topk-js/tests/upsert.spec.ts
Labels: tests, js, ready

#67 bump: topk-js@0.1.20
  topk-js/package.json
Labels: js, ready
