Repository topk-io/topk, pull requests merged in 2025-09, with the labels that each got.

#214 Release: 0.5.0
  topk-js/Cargo.toml
  topk-js/package.json
  topk-py/Cargo.toml
  topk-rs/Cargo.toml
Labels: python, js, rust, ready, self-approve

#206 feat: Verify SDKs are on the same version and validate latest dts
  .github/workflows/workflow_pr.yml
  Earthfile
Labels: ready

#228 [proto] re-map decode error
  topk-rs/build.rs
  topk-rs/src/proto/codec.rs
  topk-rs/src/proto/mod.rs
  topk-rs/tests/test_client.rs
Labels: ready

#234 Release 0.6.0
  topk-js/Cargo.toml
  topk-js/package.json
  topk-py/Cargo.toml
  topk-rs/Cargo.toml
Labels: ready

#239 [build] add explicit build triggers
  Earthfile
  topk-py/tests/test_async_collection.py
  topk-rs/build.rs
Labels: ready

#242 v0.6.1
  topk-js/Cargo.toml
  topk-js/package.json
  topk-py/Cargo.toml
  topk-rs/Cargo.toml
Labels: ready

#244 [topk-js] Add docstrings and setup typedoc
  topk-js/Cargo.toml
  topk-js/index.d.ts
  topk-js/package.json
  topk-js/src/client/collection.rs
  topk-js/src/client/collections.rs
  topk-js/src/client/mod.rs
  topk-js/src/data/collection.rs
  topk-js/src/data/list.rs
  topk-js/src/data/mod.rs
  topk-js/src/data/vector/sparse.rs
  topk-js/src/error.rs
  topk-js/src/expr/function.rs
  topk-js/src/expr/logical/binary_op.rs
  topk-js/src/expr/logical/mod.rs
  topk-js/src/expr/logical/ternary_op.rs
  topk-js/src/expr/logical/unary_op.rs
  topk-js/src/expr/text.rs
  topk-js/src/query/fn/mod.rs
  topk-js/src/query/mod.rs
  topk-js/src/query/query.rs
  topk-js/src/schema/data_type.rs
  topk-js/src/schema/field_index.rs
  topk-js/src/schema/field_spec.rs
  topk-js/src/schema/mod.rs
  topk-js/tsconfig.docs.json
  topk-js/typedoc.json
  topk-js/typedoc/custom-frontmatter-plugin.mjs
  topk-js/yarn.lock
  topk-py/Cargo.toml
  topk-rs/Cargo.toml
Labels: ready

#246 [topk-py] docstrings and docgen setup
  topk-py/docgen/__init__.py
  topk-py/docgen/main.py
  topk-py/docgen/parse.py
  topk-py/docgen/render.py
  topk-py/pyproject.toml
  topk-py/src/client/async/mod.rs
  topk-py/src/client/sync/mod.rs
  topk-py/src/data/mod.rs
  topk-py/src/expr/logical.rs
  topk-py/src/lib.rs
  topk-py/src/query/mod.rs
  topk-py/src/schema/field_spec.rs
  topk-py/src/schema/mod.rs
  topk-py/topk_sdk/__init__.pyi
  topk-py/topk_sdk/data/__init__.pyi
  topk-py/topk_sdk/error/__init__.pyi
  topk-py/topk_sdk/query/__init__.pyi
  topk-py/topk_sdk/schema/__init__.pyi
Labels: docs, python, types, ready

#250 [py and js] i8 vector
  docs/collections/create.mdx
  docs/concepts/vector-search.mdx
  docs/documents/data-constructors.mdx
  docs/documents/query.mdx
  docs/documents/upsert.mdx
  docs/sdk/topk-js/Namespace.data.mdx
  docs/sdk/topk-js/Namespace.schema.mdx
  docs/sdk/topk-py/data.mdx
  docs/sdk/topk-py/schema.mdx
  topk-js/index.d.ts
  topk-js/lib/data.d.ts
  topk-js/lib/data.js
  topk-js/lib/schema.d.ts
  topk-js/lib/schema.js
  topk-js/src/data/list.rs
  topk-js/src/data/mod.rs
  topk-js/src/data/scalar.rs
  topk-js/src/data/value.rs
  topk-js/src/schema/data_type.rs
  topk-js/src/schema/field_spec.rs
  topk-js/src/schema/mod.rs
  topk-js/tests/test_data_vector_dense.spec.ts
  topk-js/tests/test_query_vector.spec.ts
  topk-py/src/data/list.rs
  topk-py/src/data/mod.rs
  topk-py/src/data/scalar.rs
  topk-py/src/data/value.rs
  topk-py/src/schema/data_type.rs
  topk-py/src/schema/mod.rs
  topk-py/tests/test_async_collection.py
  topk-py/tests/test_collection_get.py
  topk-py/tests/test_data_vector_dense.py
  topk-py/tests/test_query_sparse_vector.py
  topk-py/tests/test_query_vector.py
  topk-py/tests/utils/dataset.py
  topk-py/topk_sdk/data/__init__.pyi
  topk-py/topk_sdk/schema/__init__.pyi
Labels: ready

#252 fix readme images for topk-py and topk-js
  topk-js/README.md
  topk-py/README.md
Labels: self-approve

#253 Release 0.6.5
  topk-js/Cargo.toml
  topk-js/package.json
  topk-py/Cargo.toml
  topk-rs/Cargo.toml
Labels: ready, self-approve
