Repository topk-io/topk, pull requests merged in 2025-05, with the labels that each got.

#70 [rust] builder methods
  topk-rs/src/data/vector.rs
  topk-rs/src/expr/function.rs
  topk-rs/src/expr/logical.rs
Labels: ready

#73 validation err
  topk-js/src/error.rs
Labels: ready

#68 Add is null and is not null operators
  topk-js/index.d.ts
  topk-js/src/expr/logical.rs
  topk-js/tests/query_logical.spec.ts
  topk-py/src/expr/logical.rs
  topk-py/tests/test_query_logical.py
  topk-rs/src/expr/logical.rs
  topk-rs/tests/test_query_logical.rs
Labels: python, tests, js, rust, ready

#86 Install Earthly
  .github/workflows/pr.yml
Labels: ready

#87 Release 0.2.1 SDKs
  topk-js/package.json
  topk-py/Cargo.toml
Labels: python, js, ready

#95 add `SlowDown` and `QuotaExceeded` errors
  topk-js/Cargo.toml
  topk-js/src/error.rs
  topk-py/Cargo.toml
  topk-py/src/error.rs
  topk-rs/src/client/collection.rs
  topk-rs/src/error.rs
  topk-rs/tests/test_upsert.rs
Labels: ready

#97 large responses, fix `topk-js` build, better errors, refactor
  .earthlyignore
  Earthfile
  topk-js/Cargo.toml
  topk-js/src/error.rs
  topk-protos/src/lib.rs
  topk-protos/src/utils.rs
  topk-py/Cargo.toml
  topk-py/src/error.rs
  topk-rs/Cargo.toml
  topk-rs/src/client/client_config.rs
  topk-rs/src/client/collection.rs
  topk-rs/src/client/collections.rs
  topk-rs/src/client/interceptor.rs
  topk-rs/src/client/mod.rs
  topk-rs/src/error.rs
  topk-rs/tests/test_get.rs
Labels: ready

#99 bump versions
  topk-js/Cargo.toml
  topk-js/package.json
  topk-py/Cargo.toml
  topk-rs/Cargo.toml
Labels: ready

#100 [topk-rs] use single `Channel` instead, bring `with_headers` back
  topk-rs/Cargo.toml
  topk-rs/src/client/client_config.rs
  topk-rs/src/client/collection.rs
  topk-rs/src/client/mod.rs
Labels: ready

#101 add `PermissionDenied` error, fix stack overflow
  topk-js/Cargo.toml
  topk-js/package.json
  topk-js/src/error.rs
  topk-py/Cargo.toml
  topk-py/src/error.rs
  topk-rs/Cargo.toml
  topk-rs/src/error.rs
Labels: ready

#103 Remove upsert_too_fast test
  topk-rs/tests/test_upsert.rs
Labels: ready

#104 implement retries
  topk-js/Cargo.toml
  topk-js/index.d.ts
  topk-js/package.json
  topk-js/src/client/mod.rs
  topk-py/Cargo.toml
  topk-py/src/client/mod.rs
  topk-rs/Cargo.toml
  topk-rs/src/client/collection.rs
  topk-rs/src/client/collections.rs
  topk-rs/src/client/config.rs
  topk-rs/src/client/mod.rs
  topk-rs/src/client/retry.rs
  topk-rs/src/error.rs
  topk-rs/src/lib.rs
Labels: ready

#107 fix test
  topk-rs/tests/test_collection.rs
Labels: ready
